### ISSUE TITLE
Missing R1 R2 resistor pads on right transmitter PCB

### ISSUE THREAD

**Issue by o-klp** [PhiBabin/redox-w-encoder#1]
I'm working on a redox-w-encoder build with the [redox-lipo-adapter](https://github.com/PhiBabin/Redox-Lipo-Adapter).

When debugging the left half I noticed there's two resistor spots, R1 and R2, to the left of the MCU that aren't on the right side, nor do they appear on the PCB of the upstream redox-w (ver 2.0, hot swap). I can't see them called out in the build guide either. Do they serve a purpose?

![20240226_202833](https://github.com/PhiBabin/redox-w-encoder/assets/6556190/f2eec567-de7d-4cc9-8f2c-fbeb5e83c3c6)

(see images of PCB from the upstream repo)
[ref 1](https://github.com/mattdibi/redox-keyboard/blob/master/img/redox-w-2.0-transmitters-assembly-1.jpg)
[ref 2](https://github.com/mattdibi/redox-keyboard/blob/master/img/redox-w-2.0-transmitters-assembly-2.jpg)

~More background is I finished the left transmitter but am unable to register keystrokes, nor it appears is the receiver able to connect with the transmitter. This is based on output from both `qmk console` and `hid_listen` -- both programs connect to the receiver but log nothing else after. I'm able to flash the firmware to both successfully (the output of both commands match the build guide's) and I've confirmed with a multimeter that the lipo adapter provides 3V power to the switch.~ edit: I've sorted out the left transmitter

**Comment by o-klp** [comment]
I may have found them in the pdf schematic:

![image](https://github.com/PhiBabin/redox-w-encoder/assets/6556190/ff14e1fa-eba2-430a-8c5e-40724a9af5da)

There's this note in the readme that calls out changing firmware to support an encoder on the right side. If the default is only encoder on the left side, does the PCB also need to be modified to support a second encoder?

> By default, only the right side has an encoder, [you can change that here](https://github.com/PhiBabin/redox-w-firmware/blob/master/redox-w-keyboard-basic/config/redox-w.h#L29)

**Comment by dawinSoft** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Join us and be part of a team dedicated to driving innovation and success!

## How to Apply:
To apply for this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.Yumenokanata, @lucianosb, @morningcheng, @Tensai-Sama, @fetaoily, @nenekodev, @eeeurico, @rsbondi, @wuchaofan, @vasco-santos, @fz420, @realzbc, @Leafhua, @stasb, @hpduong, @StoneRen, @zhq1943, @mokahaiku, @mintisan, @kurt-vonnegut

**Comment by PhiBabin** [comment]
Really sorry for the late reply.
The resistors are there because I was unsure if the encoder would need external pull up resistors. They don't need to be populated. I'll add a note for that in the README.
The PCB doesn't need to be modified to add support for an encoder on the left side.
